### ISSUE TITLE
JS messgen parser fails silently with improperly ordered complex message IDs

### ISSUE THREAD

**Issue by Roman-** [microavia/messgen#67]
In JS messgen parser, if the messages listed in a way that the ID of a complex message is less than the ID of one of its internal messages, the parser does not work and does not fire any error. Example:

bottle.yaml:
```yaml
id: 67
fields:
  - { name: name,   type: string }
  - { name: liquid, type: liquid }
```

liquid.yaml:
```yaml
id: 68
descr: "I am inside the bottle"
fields:
  - { name: density,      type: uint64 }
  - { name: is_coca_cola, type: uint8 }
```

Messgen would generate JS files without any warnings and successfully parse every message. However, when message "bottle" is received, it will have the following properties:

offset: NaN
isComplex: false (which is wrong)
